# Generated by Django 3.1.2 on 2020-10-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonCV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время загрузки на сайт')),
                ('doc', models.FileField(upload_to='docs/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Анкета',
                'verbose_name_plural': 'Анкеты',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Как к вам обращаться?')),
                ('email', models.EmailField(max_length=254, verbose_name='Ваш email')),
                ('message', models.TextField(verbose_name='Сообщение')),
            ],
        ),
    ]
